services:
  - type: web
    name: git-plants-backend
    env: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    plan: starter
    region: oregon
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: REDIS_URL
        sync: false
      # All Environment Variables (set in Render Dashboard)
      - key: GITHUB_CLIENT_ID
        sync: false
      - key: GITHUB_CLIENT_SECRET
        sync: false
      - key: GITHUB_CALLBACK_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: ADMIN_URL
        sync: false
      - key: REDIS_RECONNECT_DELAY_MS
        sync: false
      - key: CACHE_TTL_SECONDS
        sync: false
      - key: CACHE_PREFIX
        sync: false
      - key: GITHUB_SYNC_INTERVAL_MS
        sync: false
      - key: IS_REDIS_PRODUCTION
        sync: false
      - key: BADGE_CACHE_TTL
        sync: false

